### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to velocity_tools java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Pantera07** [Elytrium/VelocityTools#12]
Error after updating to latest Velocity
https://papermc.io/downloads#Velocity

```
[15:43:09 ERROR]: Couldn't pass ProxyInitializeEvent to velocity_tools
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry com.velocitypowered.proxy.protocol.ProtocolUtils$Direction.getProtocolRegistry(com.velocitypowered.proxy.protocol.StateRegistry, com.velocitypowered.api.network.ProtocolVersion)'
        at net.elytrium.velocitytools.fastprepare.PreparedPacketFactory.encodeId(PreparedPacketFactory.java:126) ~[?:?]
        at net.elytrium.velocitytools.fastprepare.PreparedPacketFactory.encodeSingle(PreparedPacketFactory.java:161) ~[?:?]
        at net.elytrium.velocitytools.fastprepare.PreparedPacket.prepare(PreparedPacket.java:133) ~[?:?]
        at net.elytrium.velocitytools.fastprepare.PreparedPacket.prepare(PreparedPacket.java:117) ~[?:?]
        at net.elytrium.velocitytools.hooks.HandshakeHook.reload(HandshakeHook.java:112) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:143) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:85) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$16.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT (git-8374af5a-b215)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT (git-8374af5a-b215)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT.jar:3.2.0-SNAPSHOT (git-8374af5a-b215)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by hevav** [comment]
This is an issue related to Velocity 3.2.0 snapshot. I've implemented support for 3.2.0 snapshot locally, but I can't upload it because Velocity developers broke the dependency to build the plugin for this snapshot. We sent a PR to Velocity to fix this problem.
I currently recommend using Velocity 3.1.2.
