### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to velocity_tools

### ISSUE THREAD

**Issue by lightumcc** [Elytrium/VelocityTools#19]
[21:04:10 ERROR]: Couldn't pass ProxyInitializeEvent to velocity_tools
java.lang.IllegalArgumentException: No enum constant com.velocitypowered.api.network.ProtocolVersion.MINECRAFT_1_19_2
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at com.velocitypowered.api.network.ProtocolVersion.valueOf(ProtocolVersion.java:22) ~[velocity-3.2.0-SNAPSHOT-243.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at net.elytrium.velocitytools.utils.ProtocolUtil.protocolVersionFromString(ProtocolUtil.java:29) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.elytrium.velocitytools.listeners.ProtocolBlockerPingListener.<init>(ProtocolBlockerPingListener.java:49) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:159) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:102) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$12.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-243.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-243.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-243.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by lightumcc** [comment]
velocity: velocity-3.2.0-SNAPSHOT-243
limboapi-1.1.11.jar

**Comment by AVuTuVA** [comment]
Put instead of 1.19.2, 1.19.1 (they have the same protocols)

**Comment by lightumcc** [comment]
so do you mean this plugin isn't available for 1.19.2?

> Put instead of 1.19.2, 1.19.1 (they have the same protocols)

**Comment by AVuTuVA** [comment]
Show config

**Comment by lightumcc** [comment]
version: "1.1.9"
# Available serializers:
# LEGACY_AMPERSAND - "&c&lExample &c&9Text".
# LEGACY_SECTION - "§c§lExample §c§9Text".
# MINIMESSAGE - "<bold><red>Example</red> <blue>Text</blue></bold>". (https://webui.adventure.kyori.net/)
# GSON - "[{"text":"Example","bold":true,"color":"red"},{"text":" ","bold":true},{"text":"Text","bold":true,"color":"blue"}]". (https://minecraft.tools/en/json_text.php/)
# GSON_COLOR_DOWNSAMPLING - Same as GSON, but uses downsampling.
serializer: LEGACY_AMPERSAND

main:
  # VelocityTools will consume more RAM if this option is enabled, but compatibility with other plugins will be better
  # Enable it if you have a plugin installed that bypasses compression (e.g. Geyser)
  save-uncompressed-packets: true

# Don't use \n, use {NL} for new line. Ampersand (&) color codes are supported too.

# 
# Permissions:
#   │
#   └── Commands:
#       │
#       ├── /velocitytools reload
#       │   └── velocitytools.admin.reload
#       ├── /alert
#       │   └── velocitytools.command.alert
#       ├── /find
#       │   └── velocitytools.command.find
#       ├── /send
#       │   └── velocitytools.command.send
#       └── /hub
#           ├── velocitytools.command.hub
#           └── velocitytools.command.hub.bypass.<servername> (disabled-servers bypass permission)
# 
commands:
  alert:
    enabled: true
    prefix: "&8[&cCreatech Alert 全局广播&8] &r{0}"
    message-needed: "&cYou must supply the message."
    empty-proxy: "&cNo one is connected to this proxy!"
  find:
    enabled: true
    username-needed: "&cYou must supply the username."
    player-online-at: "&6{0} &fis online at &6{1}"
    player-not-online: "&6{0} &fis not online."
  send:
    enabled: true
    console: "CONSOLE"
    not-enough-arguments: "&fNot enough arguments. Usage: &6/send <server|player|all|current> <target>"
    # Set to "" to disable.
    you-got-summoned: "&fSummoned to &6{0} &fby &6{1}"
    player-not-online: "&6{0} &fis not online."
    callback: "&aAttempting to send {0} players to {1}"
  hub:
    enabled: true
    servers:
      - "survival"
    # Set to "" to disable.
    you-got-moved: "&a你被移动至主服务器!"
    disabled-server: "&c你不能在这里使用这个指令."
    disabled-servers:
      - "foo"
      - "bar"
    aliases:
      - "hub"
      - "lobby"
      - "survival"

tools:
  # Hides the Legacy Ping message.
  disable-legacy-ping: true
  # Hides the "... provided invalid protocol ..." message. Helps with some types of attacks. (https://media.discordapp.net/attachments/868930650537857024/921383075454259300/unknown.png)
  disable-invalid-protocol: true
  protocol-blocker:
    block-join: true
    block-ping: true
    # If true, all protocols except those listed below will be blocked.
    whitelist: true
    # You can set either a protocol number here (e.g. '340' for 1.12.2) or a Minecraft version below (e.g. '1.12.2')
    # You can find a list of protocols here: https://wiki.vg/Protocol_version_numbers
    protocols:
      - 759
      - 760
      - 761
      - 762
    # List of versions:
    # 1.7.2, 1.7.6, 1.8, 1.9, 1.9.1, 1.9.2, 1.9.4, 1.10, 1.11, 1.11.1, 1.12, 1.12.1, 1.12.2,
    # 1.13, 1.13.1, 1.13.2, 1.14, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.15, 1.15.1, 1.15.2,
    # 1.16, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.17, 1.17.1, 1.18, 1.18.2, 1.19, 1.19.1, 1.19.3, LATEST
    versions:
      - "1.19.2"
    minimum-version: "1.19"
    maximum-version: "LATEST"
    # For "block-ping" option.
    brand: "版本不支持!"
    # For "block-ping", set to "" to disable.
    motd: "&c版本不支持!{NL}&e请使用1.19及以上."
    # For "block-joining" option.
    kick-reason: "&c你的版本不支持!"
  brand-changer:
    rewrite-in-ping: true
    rewrite-in-game: true
    ping-brand: "Createch Proxy 2023.2.16"
    # For ping.
    show-always: false
    # {0} - Original server brand (e.g. Paper).
    in-game-brand: "Createch Proxy 22023.2.16"
  # Doesn't work with srv records.
  hostnames-manager:
    block-join: true
    block-ping: false
    # Connections IP logging.
    debug: false
    # For "debug" option.
    show-blocked-only: false
    # For "block-joining" option, set to "" to show the default reason.
    kick-reason: "&c请不要使用IP或其他域名!{NL}请使用xxx.xxx.com"
    whitelist: true
    # IP Addresses starting with "127." or equal to "localhost" will be blocked.
    block-local-addresses: true
    # DoMaIn.net will be similar to domain.net.
    ignore-case: true
    hostnames:
      - "xxx.xxxx.com"

    # List of IP addresses that will bypass this check.
    ignored-ips:
      - "xxx.xxx.xxx"

**Comment by AVuTuVA** [comment]
![image](https://user-images.githubusercontent.com/66278054/226369276-b334635f-6ef4-4c71-991b-7dfd41306663.png)
    versions:
      - "1.19.1"

**Comment by lightumcc** [comment]
Oh, thanks!
