### ISSUE TITLE
Error on Velocity Launch

### ISSUE THREAD

**Issue by rktfier** [Elytrium/VelocityTools#2]
Java : 

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

```

OS : Windows 10 Enterprise

Velocity : 3.0.1

```
[17:28:50 ERROR]: Couldn't pass ProxyInitializeEvent to velocity_tools
java.lang.NullPointerException: null
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:150) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:83) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by mdxd44** [comment]
> Java :
> 
> ```
> openjdk version "11.0.11" 2021-04-20
> OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
> OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
> ```
> 
> OS : Windows 10 Enterprise
> 
> Velocity : 3.0.1
> 
> ```
> [17:28:50 ERROR]: Couldn't pass ProxyInitializeEvent to velocity_tools
> java.lang.NullPointerException: null
>         at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:150) ~[?:?]
>         at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:83) ~[?:?]
>         at net.elytrium.velocitytools.Lmbda$4.execute(Unknown Source) ~[?:?]
>         at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1]
>         at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1]
>         at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
>         at java.lang.Thread.run(Unknown Source) [?:?]
> ```

sorry for late, answer but the problem is related to the config, delete the old one to generate a new one
