### ISSUE TITLE
Strange errors happens with the latest version in Velocity 1.20.2 on startup

### ISSUE THREAD

**Issue by SimonMage** [Elytrium/VelocityTools#28]
Here the error;

[15:49:15 ERROR]: Couldn't pass ProxyInitializeEvent to velocity-tools
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.packet.Disconnect com.velocitypowered.proxy.protocol.packet.Disconnect.create(net.kyori.adventure.text.Component, com.velocitypowered.api.network.ProtocolVersion, boolean)'
        at net.elytrium.velocitytools.hooks.HandshakeHook.lambda$reload$0(HandshakeHook.java:113) ~[?:?]
        at net.elytrium.velocitytools.3rdparty.net.elytrium.fastprepare.PreparedPacket.prepare(PreparedPacket.java:133) ~[?:?]
        at net.elytrium.velocitytools.3rdparty.net.elytrium.fastprepare.PreparedPacket.prepare(PreparedPacket.java:119) ~[?:?]
        at net.elytrium.velocitytools.hooks.HandshakeHook.reload(HandshakeHook.java:113) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:179) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:115) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$28.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-294.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by hevav** [comment]
Update the plugin
