### ISSUE TITLE
Error with velocity 3.3.0-320

### ISSUE THREAD

**Issue by dshimen** [Elytrium/VelocityTools#29]
Hey, after update from #318 to #320 build, players can't connect to server with that error:
[12:40:25] [Netty epoll Worker #0/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]:  [server connection] DShimen -> lobby has connected
[12:40:25] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]:  [server connection] DShimen -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.ConfigSessionHandler@1b8b167e
net.elytrium.velocitytools.3rdparty.net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
	at net.elytrium.velocitytools.hooks.PluginMessageHook.handle(PluginMessageHook.java:61) ~[?:?]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:152) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-320.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.connection.MinecraftConnection.write(java.lang.Object)'
	at net.elytrium.velocitytools.hooks.PluginMessageHook.handle(PluginMessageHook.java:57) ~[?:?]
	... 39 more
	
	
	There were changes with some packets so maybe that's bcs (in build #320)
	
	Ps. Using latest 1.2.0 velocity tools

**Comment by TheFaik** [comment]
Also!

**Comment by TheFaik** [comment]
Please fix!

**Comment by hevav** [comment]
Release 1.2.0 was rebuilded with new Velocity Proxy code, re-download the plugin
