### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/VelocityTools#32]
Couldn't pass ProxyInitializeEvent to velocity-tools
java.lang.IllegalArgumentException: No enum constant com.velocitypowered.api.network.ProtocolVersion.MINECRAFT_1_20_1
        at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at com.velocitypowered.api.network.ProtocolVersion.valueOf(ProtocolVersion.java:22) ~[Velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at net.elytrium.velocitytools.utils.ProtocolUtil.protocolVersionFromString(ProtocolUtil.java:29) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at net.elytrium.velocitytools.listeners.ProtocolBlockerPingListener.<init>(ProtocolBlockerPingListener.java:49) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:172) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:115) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$28.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[Velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[Velocity.jar:3.3.0-SNAPSHOT (git-08c03aae-b320)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by TheFaik** [comment]
?
