### ISSUE TITLE
error velocity-3.3.0-330

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/VelocityTools#36]
Couldn't pass ProxyInitializeEvent to velocity-tools
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/Handshake
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:179) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:115) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$22.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.Handshake
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[Velocity.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 21 more

**Comment by BlueTree242** [comment]
Can confirm, same error is produced even with the latest 1.2.1
