### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by TizoCraft** [Elytrium/VelocityTools#4]
[02:56:47 INFO]: Booting up Velocity 3.0.1...
[02:56:47 INFO]: Loading localizations...
[02:56:48 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[02:56:48 INFO]: Loading plugins...
[02:56:49 INFO]: Loaded plugin kaurivpn 1.5.0 by funkemunky
[02:56:49 INFO]: Loaded plugin spark 1.6.2 by Luck
[02:56:49 INFO]: Loaded plugin velocity_tools 1.1.4 by mdxd44, hevav
[02:56:49 INFO]: Loaded 3 plugins
[02:56:49 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Loading config...
[02:56:49 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Starting AntiVPN services...
[02:56:49 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Using databaseType MySQL...
[02:56:49 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Registering commands...
[02:56:49 ERROR]: Couldn't pass ProxyInitializeEvent to velocity_tools
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/connection/client/LoginInboundConnection
        at net.elytrium.velocitytools.listeners.ProtocolBlockerJoinListener.<init>(ProtocolBlockerJoinListener.java:42) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.reload(VelocityTools.java:136) ~[?:?]
        at net.elytrium.velocitytools.VelocityTools.onProxyInitialization(VelocityTools.java:81) ~[?:?]
        at net.elytrium.velocitytools.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.connection.client.LoginInboundConnection
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:83) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:60) ~[velocity-3.0.1.jar:3.0.1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 10 more
[02:56:49 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:23596
[02:56:49 INFO]: Done (3.45s)

**Comment by TizoCraft** [comment]
btw i dont use velocity locally where the server is on. i run it on a other server
